<div class="junipeer">
    <div class="logo">

            <div style="font-size:16px;">
                Our goal is to create the most stable and fast integrations, together with the best possible partners. <br />
                We want to allow more companies to work more efficient and help them grow.

                <br />
                <small>Our software allows us to integrate systems quicker and more flexible than other platforms.</small> ​
            </div>

            <br />

            Are you interested on adding custom functionality to your integration? Feel free to contact us! <br /> <br />

            <b>E-mail:</b><br />
            <a target="_blank" href="https://junipeer.se/contact">info@junipeer.io</a> <br /> <br />

            <b>Website:</b> <br />
            <a target="_blank" href="https://junipeer.io/">https://junipeer.io</a> <br />
    </div>

</div>
